apiVersion: apps/v1
kind: Deployment
metadata:
  name: zkillsync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zkillsync
  template:
    metadata:
      labels:
        app: zkillsync
    spec:
      containers:
      - name: zkillsync
        image: ghcr.io/evebot-tools/zkillsync
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: ENVIRONMENT
              name: evetools-secrets
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: SENTRY_ZKILLSYNC
              name: evetools-secrets